# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4771113484d1bd85fd76abc172fcda2ddf96f326edb065933777ca53f817d3fa8bc00881049d4dddce9ac7d4ce310918c908f2202379fcca39e7bd90c2e214f1

test:
  secret_key_base: 8af5660bdd3e106658c9ace77e3796fcce456701e9395072d781e960fd20172bb81f84d7085c78aaaf0d8da9b6786fec742a07cc4d2cc4b78d5f677d2dff46cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
